Repository NITK-KODE/cms-api, pull requests merged in 2021-09, with the labels that each got.

#14 #4 update
  .env.sample
  .eslintrc.json
  package-lock.json
  package.json
  src/app.js
  src/cloudinary/index.js
  src/controllers/admin.js
  src/controllers/awards.js
  src/controllers/events.js
  src/controllers/mod.js
  src/controllers/organizations.js
  src/controllers/users.js
  src/middlewares/.gitkeep
  src/middlewares/authentication.js
  src/middlewares/authorization.js
  src/middlewares/userMw.js
  src/middlewares/userTypeMw.js
  src/models/award.js
  src/models/event.js
  src/models/organization.js
  src/models/user.js
  src/routes/admin.js
  src/routes/awards.js
  src/routes/events.js
  src/routes/mod.js
  src/routes/organizations.js
  src/routes/users.js
  src/services/auth/.gitkeep
  src/services/db.js
  src/utilities/ExpressError.js
Labels: enhancement, help wanted

#30 Fix severe vulnearability fix return issues and add comments
  src/app.js
  src/controllers/admin.js
  src/controllers/awards.js
  src/controllers/events.js
  src/controllers/institutes.js
  src/controllers/mod.js
  src/controllers/organizations.js
  src/controllers/users.js
  src/middlewares/authentication.js
  src/middlewares/authorization.js
  src/models/event.js
  src/models/institute.js
  src/models/organization.js
  src/routes/Institutes.js
  src/routes/awards.js
  src/routes/events.js
  src/routes/organizations.js
  src/routes/users.js
  src/services/db.js
  src/utilities/ExpressError.js
  src/utilities/catchasync.js
Labels: bug, help wanted, discussion

#37 Create CONTRIBUTING.md
  .github/CONTRIBUTING.MD
Labels: hacktoberfest-approved
