Repository NITK-KODE/cms-api, pull requests merged in 2021-10, with the labels that each got.

#46 Added heroku.yml to deploy container to heroku #45
  heroku.yml
Labels: hacktoberfest-approved

#44 refactoring controllers
  src/controllers/awards.js
  src/controllers/events.js
  src/controllers/organizations.js
  src/middlewares/controllers/awards.js
  src/middlewares/controllers/events.js
  src/middlewares/controllers/organizations.js
Labels: enhancement, hacktoberfest, hacktoberfest-approved

#53 institute validation
  src/validators/institutes.js
Labels: hacktoberfest, ✅ Approved

#55 Update users.js
  src/validators/users.js
Labels: ✅ Approved
